import { CartoonCharacterId, ThemeConfig } from '../types';

export const DISNEY_THEMES: Record<CartoonCharacterId, ThemeConfig> = {
  elsa: {
    id: 'elsa',
    name: 'Queen Elsa',
    movie: 'Frozen / The Fifth Spirit',
    tagline: 'The cold never bothered my math anyway! ❄️',
    primaryColor: '#0284C7', // Frost Sky Blue
    accentColor: '#38BDF8', // Ice Shimmer
    bgGradient: 'from-sky-950/70 via-indigo-950/60 to-slate-950',
    calculatorBody: 'bg-gradient-to-b from-sky-600 via-sky-700 to-indigo-900 border-4 border-cyan-200 shadow-[0_20px_60px_rgba(56,189,248,0.4)]',
    displayBg: 'bg-cyan-50 text-sky-950 border-4 border-cyan-200 shadow-inner',
    buttonNumberBg: 'bg-white/95 text-slate-900 shadow-[0_6px_0_#93C5FD] active:translate-y-1 active:shadow-[0_2px_0_#93C5FD]',
    buttonNumberHover: 'hover:bg-cyan-50',
    buttonNumberText: 'text-slate-900',
    buttonOperatorBg: 'bg-cyan-400 text-slate-950 shadow-[0_6px_0_#0284C7] active:translate-y-1 active:shadow-[0_2px_0_#0284C7]',
    buttonOperatorHover: 'hover:bg-cyan-300',
    buttonOperatorText: 'text-slate-950',
    buttonScientificBg: 'bg-sky-900/80 text-cyan-200 border border-cyan-400/40 shadow-[0_4px_0_#075985]',
    buttonScientificText: 'text-cyan-100',
    buttonEqualsBg: 'bg-gradient-to-r from-cyan-400 via-sky-400 to-indigo-500 text-white shadow-[0_6px_0_#0369A1]',
    buttonSpecialBg: 'bg-sky-100 text-sky-950 shadow-[0_6px_0_#BAE6FD]',
    particleType: 'snowflake',
    catchphrases: {
      greeting: 'The cold never bothered my math anyway! ❄️',
      numberTap: [
        'Into the unknown!',
        'Crystal clear!',
        'Show yourself!',
        'Ice magic at work!',
        'Glistening snowflake!',
        'Freeze the moment!',
      ],
      operatorTap: [
        'Conjuring an ice fractal!',
        'Casting a frost wave!',
        'Connecting the frozen winds!',
        'Glacial calculation!',
      ],
      trigTap: [
        'Measuring the angles of the ice palace!',
        'Sinusoidal frost wave!',
        'Harmonic crystal resonance!',
      ],
      equals: [
        'Let it go! The answer is revealed!',
        'The snow glows white with truth!',
        'Flawless ice crystal solution!',
        'A magnificent Fifth Spirit triumph!',
      ],
      clear: [
        'A blizzard blows it all away! Poof! ❄️',
        'Melted away into fresh winter snow!',
        'Clear as morning icicles!',
      ],
      easterEgg: [
        'The Fifth Spirit has awakened!',
        'The secret ice memory of Ahtohallan!',
      ],
    },
  },
  moana: {
    id: 'moana',
    name: 'Moana',
    movie: 'Moana of Motunui',
    tagline: 'See the line where the sky meets the sea? It calls me! 🌊',
    primaryColor: '#0D9488', // Tropical Teal
    accentColor: '#10B981', // Heart of Te Fiti Green
    bgGradient: 'from-teal-950/70 via-cyan-950/60 to-slate-950',
    calculatorBody: 'bg-gradient-to-b from-teal-600 via-emerald-700 to-cyan-900 border-4 border-emerald-300 shadow-[0_20px_60px_rgba(13,148,136,0.4)]',
    displayBg: 'bg-emerald-50 text-teal-950 border-4 border-emerald-200 shadow-inner',
    buttonNumberBg: 'bg-amber-50/95 text-slate-900 shadow-[0_6px_0_#A7F3D0] active:translate-y-1 active:shadow-[0_2px_0_#A7F3D0]',
    buttonNumberHover: 'hover:bg-emerald-100/60',
    buttonNumberText: 'text-slate-900',
    buttonOperatorBg: 'bg-emerald-400 text-teal-950 shadow-[0_6px_0_#059669] active:translate-y-1 active:shadow-[0_2px_0_#059669]',
    buttonOperatorHover: 'hover:bg-emerald-300',
    buttonOperatorText: 'text-teal-950',
    buttonScientificBg: 'bg-teal-900/80 text-emerald-200 border border-emerald-400/40 shadow-[0_4px_0_#115E59]',
    buttonScientificText: 'text-emerald-100',
    buttonEqualsBg: 'bg-gradient-to-r from-emerald-400 via-teal-500 to-cyan-500 text-white shadow-[0_6px_0_#065F46]',
    buttonSpecialBg: 'bg-amber-100 text-amber-950 shadow-[0_6px_0_#FDE68A]',
    particleType: 'flower',
    catchphrases: {
      greeting: 'I am Moana of Motunui! Ready to wayfind through math? 🌊',
      numberTap: [
        'I know every turn of the tide!',
        'Wayfinder step!',
        'The ocean chose this number!',
        'Island courage!',
        'Smooth voyaging!',
        'Catching the trade winds!',
      ],
      operatorTap: [
        'Setting the course with the stars!',
        'Riding the big ocean swell!',
        'Navigating currents!',
      ],
      trigTap: [
        'Measuring star angles with an outstretched hand!',
        'Ocean tide sinusoidal wave!',
        'Celestial navigation trajectory!',
      ],
      equals: [
        'How Far I\'ll Go! We reached the shore!',
        'The Heart of Te Fiti is restored!',
        'A master wayfinder calculation!',
        'Maui is impressed! Chee-hoo!',
      ],
      clear: [
        'The ocean wave washes the shore clean! 🌊',
        'New horizon, fresh voyage!',
        'Ready to set sail again!',
      ],
      easterEgg: [
        'Maui\'s magical fish hook glows!',
        'You found the Heart of Te Fiti! 💚',
      ],
    },
  },
  anna: {
    id: 'anna',
    name: 'Princess Anna',
    movie: 'Frozen / Queen of Arendelle',
    tagline: 'For the first time in forever, math is magical! 🌻',
    primaryColor: '#BE123C', // Nordic Cranberry / Magenta
    accentColor: '#F59E0B', // Sunflower Gold
    bgGradient: 'from-rose-950/70 via-amber-950/50 to-slate-950',
    calculatorBody: 'bg-gradient-to-b from-rose-600 via-pink-700 to-amber-900 border-4 border-amber-300 shadow-[0_20px_60px_rgba(190,18,60,0.4)]',
    displayBg: 'bg-rose-50 text-rose-950 border-4 border-amber-200 shadow-inner',
    buttonNumberBg: 'bg-white/95 text-slate-900 shadow-[0_6px_0_#FECDD3] active:translate-y-1 active:shadow-[0_2px_0_#FECDD3]',
    buttonNumberHover: 'hover:bg-rose-50',
    buttonNumberText: 'text-slate-900',
    buttonOperatorBg: 'bg-amber-400 text-rose-950 shadow-[0_6px_0_#D97706] active:translate-y-1 active:shadow-[0_2px_0_#D97706]',
    buttonOperatorHover: 'hover:bg-amber-300',
    buttonOperatorText: 'text-rose-950',
    buttonScientificBg: 'bg-rose-900/80 text-amber-200 border border-amber-400/40 shadow-[0_4px_0_#881337]',
    buttonScientificText: 'text-amber-100',
    buttonEqualsBg: 'bg-gradient-to-r from-rose-500 via-amber-500 to-pink-500 text-white shadow-[0_6px_0_#9F1239]',
    buttonSpecialBg: 'bg-amber-100 text-amber-950 shadow-[0_6px_0_#FDE68A]',
    particleType: 'heart',
    catchphrases: {
      greeting: 'For the first time in forever, math is so much fun! 🌻',
      numberTap: [
        'Chocolate!',
        'Love is an open door!',
        'Do you want to build a snowman?',
        'Look at that lovely number!',
        'Oh, totally!',
        'Arendelle high five!',
      ],
      operatorTap: [
        'Putting all our hearts together!',
        'Sister magic at work!',
        'Adding warm hugs!',
      ],
      trigTap: [
        'Dancing in circles at the coronation ball!',
        'Trig magic! Elsa would be so proud!',
        'Spinning with the autumn breeze!',
      ],
      equals: [
        'Some things never change, like you being brilliant!',
        'We solved it together! Warm hugs!',
        'Total perfection! Let\'s eat cake!',
        'Queen of the numbers!',
      ],
      clear: [
        'Fresh start! Can we have chocolate now?',
        'Tidying up the castle hallway!',
        'All squeaky clean for summer!',
      ],
      easterEgg: [
        'Coronation Day celebration! 👑',
        'Sven and Kristoff gave you a carrot!',
      ],
    },
  },
  olaf: {
    id: 'olaf',
    name: 'Olaf',
    movie: 'Frozen / In Summer',
    tagline: 'Hi, I\'m Olaf and I like warm hugs and happy math! ⛄',
    primaryColor: '#F59E0B',
    accentColor: '#38BDF8',
    bgGradient: 'from-amber-950/60 via-sky-950/60 to-slate-950',
    calculatorBody: 'bg-gradient-to-b from-sky-500 via-amber-500 to-orange-600 border-4 border-amber-300 shadow-[0_20px_60px_rgba(245,158,11,0.4)]',
    displayBg: 'bg-amber-50 text-slate-950 border-4 border-sky-200 shadow-inner',
    buttonNumberBg: 'bg-white/95 text-slate-900 shadow-[0_6px_0_#BAE6FD] active:translate-y-1 active:shadow-[0_2px_0_#BAE6FD]',
    buttonNumberHover: 'hover:bg-amber-50',
    buttonNumberText: 'text-slate-900',
    buttonOperatorBg: 'bg-sky-400 text-slate-950 shadow-[0_6px_0_#0284C7] active:translate-y-1 active:shadow-[0_2px_0_#0284C7]',
    buttonOperatorHover: 'hover:bg-sky-300',
    buttonOperatorText: 'text-slate-950',
    buttonScientificBg: 'bg-sky-900/80 text-amber-200 border border-amber-300/40 shadow-[0_4px_0_#075985]',
    buttonScientificText: 'text-amber-100',
    buttonEqualsBg: 'bg-gradient-to-r from-amber-400 via-orange-400 to-sky-400 text-slate-950 shadow-[0_6px_0_#C2410C]',
    buttonSpecialBg: 'bg-orange-100 text-orange-950 shadow-[0_6px_0_#FED7AA]',
    particleType: 'magic',
    catchphrases: {
      greeting: 'Hi everyone! I\'m Olaf, and I love warm math! ⛄',
      numberTap: [
        'I don\'t have a skull... or bones!',
        'In summer!',
        'Look at that bouncy number!',
        'Hands up, carrot out!',
        'Winter flurry!',
        'Giggle giggle!',
      ],
      operatorTap: [
        'Splish splash in a puddle!',
        'Putting numbers together like snowballs!',
        'Careful, don\'t knock my buttons off!',
      ],
      trigTap: [
        'Ooh, curvy waves! Just like tanning on the beach!',
        'Wavy sunbeams and trigonometrics!',
        'Bouncing across the rainbow!',
      ],
      equals: [
        'Happy birthday! Wait, no, happy answer!',
        'Big warm hugs for the right answer!',
        'I\'m a math snowman genius!',
      ],
      clear: [
        'My parts fell off! All put together again!',
        'Fresh flurry on the snowman!',
      ],
      easterEgg: [
        'Samantha? I don\'t even know a Samantha!',
        'My very own personal flurry!',
      ],
    },
  },
};

export const DISNEY_EASTER_EGGS: Record<string, string> = {
  '0': 'Olaf\'s Summer Melting Point ☀️',
  '1': 'One True Sister Love (Frozen) 💖',
  '2': 'Anna & Elsa - The Two Queens of Arendelle 👑',
  '3': 'Three Little Snowgies (Frozen Fever) ⛄',
  '4': 'Four Elements of the Enchanted Forest 🌪️🔥💧🪨',
  '5': 'The Fifth Spirit (Elsa & the Magic of Nature) ❄️',
  '7': 'Seven Seas Moana Navigates Across 🌊',
  '2013': 'Frozen Premiere Year! Let It Go! ❄️',
  '2016': 'Moana Premiere Year! How Far I\'ll Go! 🌊',
  '2019': 'Frozen 2 Premiere Year! Into the Unknown! 🍂',
  '2024': 'Moana 2 Premiere Year! The Ocean Calls! 🌺',
  '3.14159': 'Pi: The Endless Circle of Life 🥧',
  '2.71828': 'Euler: Natural Growth of the Magic Forest 🌲',
};
